# Generated by Django 6.0.6 on 2026-06-11 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'permissions': [('share_document', 'Can share document')]},
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='Document_Management_System.document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to='Document_Management_System.userprofile')),
                ('shared_with_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_document_shares', to='Document_Management_System.usergroup')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_document_shares', to='Document_Management_System.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('shared_with_user__isnull', False), ('shared_with_group__isnull', True)), models.Q(('shared_with_user__isnull', True), ('shared_with_group__isnull', False)), _connector='OR'), name='document_share_single_target'), models.UniqueConstraint(condition=models.Q(('shared_with_user__isnull', False)), fields=('document', 'shared_with_user'), name='unique_document_share_user'), models.UniqueConstraint(condition=models.Q(('shared_with_group__isnull', False)), fields=('document', 'shared_with_group'), name='unique_document_share_group')],
            },
        ),
    ]
