# Generated by Django 6.0.6 on 2026-06-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Management_System', '0003_add_session_token_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionToken',
        ),
    ]
