"""
Django settings for DMS project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

from datetime import timedelta
import os
from pathlib import Path
import dj_database_url
from rest_framework.settings import api_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# SAFE DATABASE ROUTING (With Explicit Cloud/Local Fallbacks)
# ==============================================================================
IS_RENDER = 'RENDER' in os.environ or 'DATABASE_URL' in os.environ

if IS_RENDER and os.getenv('DATABASE_URL'):
    # Prioritize live cloud configuration if Render has fully injected it
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600)
    }
else:
    # Safe fallback initialization structure for local PC development or initial build stages
    def load_dotenv(path):
        if not path.exists():
            return
        for raw_line in path.read_text(encoding='utf-8').splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))

    load_dotenv(BASE_DIR / '.env')

    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'DMS_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# ==============================================================================
# CORE DEPLOYMENT SECURITY SETTINGS
# ==============================================================================
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-mjshl(^7w$1+38uc^kw*!_=+sxm_mq%d@z(=%*yqx5ygjfgt+i')
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Dynamic host validation alignment
ALLOWED_HOSTS = [os.getenv('RENDER_EXTERNAL_HOSTNAME', '*')]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'DMS.Document_Management_System',
    'knox',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# ==============================================================================
# AUTOMATIC CLOUD SUPERUSER GENERATION
# ==============================================================================
if IS_RENDER:
    from django.db.models.signals import post_migrate
    from django.dispatch import receiver

    @receiver(post_migrate)
    def create_production_admin(sender, **kwargs):
        # Prevent running this multiple times for different sub-apps
        if sender.name == 'django.contrib.auth':
            from django.contrib.auth import get_user_model
            User = get_user_model()
            
            # Choose your preferred credentials here
            admin_username = 'admin'
            admin_email = 'admin@example.com'
            admin_password = 'admin@123'  # Change this to a secure password!

            if not User.objects.filter(username=admin_username).exists():
                print("Creating cloud infrastructure superuser account...")
                User.objects.create_superuser(
                    username=admin_username, 
                    email=admin_email, 
                    password=admin_password
                )
                print("Superuser created successfully.")

ROOT_URLCONF = 'DMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DMS.wsgi.application'

# REST API Layer Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'knox.auth.TokenAuthentication',
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ]
}

REST_KNOX = {
  'SECURE_HASH_ALGORITHM': 'hashlib.sha512',
  'AUTH_TOKEN_CHARACTER_LENGTH': 64,
  'TOKEN_TTL': timedelta(hours=10),
  'USER_SERIALIZER': 'knox.serializers.UserSerializer',
  'TOKEN_LIMIT_PER_USER': None,
  'AUTO_REFRESH': False,
  'AUTO_REFRESH_MAX_TTL': None,
  'MIN_REFRESH_INTERVAL': 60,
  'AUTH_HEADER_PREFIX': 'Token',
  'EXPIRY_DATETIME_FORMAT': api_settings.DATETIME_FORMAT,
  'TOKEN_MODEL': 'knox.AuthToken',
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Redis Cache Architecture
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
    }
}

# Globalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Production Static Asset Configuration
STATIC_URL = '/static/'
STATIC_ROOT = str(BASE_DIR / 'staticfiles')

# Enable WhiteNoise compression and caching for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
